# Cloud Build - Staging Environment
# Deploy para ambiente de staging/homologação

substitutions:
  _ENV: 'staging'
  _SERVICE_NAME: 'ollama-service-staging'
  _REGION: 'us-east4'
  _CPU: '4'
  _MEMORY: '8Gi'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '5'

steps:
  # --- Build da Imagem ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg ENV=${_ENV} \
          --build-arg OLLAMA_MODELS=qwen3:4b \
          -t gcr.io/$PROJECT_ID/ollama-custom-${_ENV}:$COMMIT_SHA \
          -t gcr.io/$PROJECT_ID/ollama-custom-${_ENV}:latest \
          -f Dockerfile .
    timeout: 2400s # 40 minutos para download dos modelos

  # --- Push para Container Registry ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-sha'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama-custom-${_ENV}:$COMMIT_SHA']
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama-custom-${_ENV}:latest']
    waitFor: ['build-image']

  # --- Deploy no Cloud Run ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloudrun'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/$PROJECT_ID/ollama-custom-${_ENV}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--ingress=internal'
      - '--cpu=${_CPU}'
      - '--memory=${_MEMORY}'
      - '--no-cpu-throttling'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--timeout=3600s'
      - '--set-env-vars=ENVIRONMENT=${_ENV},OLLAMA_KEEP_ALIVE=24h'
      - '--no-allow-unauthenticated' # Staging requer autenticação
    waitFor: ['push-sha', 'push-latest']

  # --- Teste de Health Check ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "✅ Deploy completado com sucesso para ${_ENV}"
        echo "🔍 Serviço: ${_SERVICE_NAME}"
        echo "📍 Região: ${_REGION}"
        gcloud run services describe ${_SERVICE_NAME} --region=${_REGION} --format='value(status.url)'
    waitFor: ['deploy-cloudrun']

# Imagens resultantes
images:
  - 'gcr.io/$PROJECT_ID/ollama-custom-${_ENV}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ollama-custom-${_ENV}:latest'

# Configurações globais
timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
