# Cloud Build - Sandbox Environment
# Deploy para ambiente de sandbox

substitutions:
  _ENV: 'sandbox'
  _SERVICE_NAME: 'brh-ollama-sbx'
  _REGION: 'us-east4'
  _PROJECT_ID: 'brh-sbx-479520'
  _ARTIFACT_REGISTRY: 'us-east4-docker.pkg.dev'
  _REPOSITORY: 'cloud-run-source-deploy/brh-ollama'
  _MODELS: 'qwen2.5:3b-instruct'
  _CPU: '3'
  _MEMORY: '6Gi'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '1'

steps:
  # --- Build da Imagem ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg ENV=${_ENV} \
          --build-arg MODELS_LIST="${_MODELS}" \
          -t ${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA \
          -t ${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest \
          -f Dockerfile .
    timeout: 2400s # 40 minutos para download dos modelos

  # --- Push para Artifact Registry ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-sha'
    args: ['push', '${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA']
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args: ['push', '${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest']
    waitFor: ['build-image']

  # --- Deploy no Cloud Run ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloudrun'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--project=${_PROJECT_ID}'
      - '--ingress=internal'
      - '--cpu=${_CPU}'
      - '--memory=${_MEMORY}'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--timeout=300'
      - '--set-env-vars=ENVIRONMENT=${_ENV},OLLAMA_HOST=0.0.0.0:11434,OLLAMA_KEEP_ALIVE=24h,OLLAMA_MODELS=/models'
      - '--no-allow-unauthenticated'
      - '--concurrency=80'
      - '--port=8080'
    waitFor: ['push-sha', 'push-latest']

  # --- Teste de Health Check ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "✅ Deploy completado com sucesso para ${_ENV}"
        echo "🔍 Serviço: ${_SERVICE_NAME}"
        echo "📍 Região: ${_REGION}"
        gcloud run services describe ${_SERVICE_NAME} --region=${_REGION} --format='value(status.url)'
    waitFor: ['deploy-cloudrun']

# Imagens resultantes
images:
  - '${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
  - '${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

# Configurações globais
timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
